plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-csw8.github.io
baseurl: "/w24"

course: "CMPSCW 8"
qtr: "W24"
instructor: "Richert Wang" 
quarter: "Winter 2024"
piazza_url: 
gauchospace_course_page:
gradescope_class_url:

github_url: https://github.com/ucsb-csw8/w24

start_week: 1
start_date: 2024-01-07 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

cal_dates: >                                                                    
  [                                                                            
    {"label":"W24 1st day of instruction", "date":"2024-01-08" },
    {"label":"MLK Jr. Day", "date":"2024-01-15" },
    {"label":"Presidents' Day", "date":"2024-02-19" },
    {"label":"zyBooks Week 1 and 2 due", "date":"2024-01-21" },
    {"label":"zyBooks Week 3 due", "date":"2024-01-28" },
    {"label":"zyBooks Week 4 due", "date":"2024-02-04" },
    {"label":"zyBooks Week 5 due", "date":"2024-02-11" },
    {"label":"zyBooks Week 6 due", "date":"2024-02-18" },
    {"label":"zyBooks Week 7 due", "date":"2024-02-25" },
    {"label":"zyBooks Week 8 due", "date":"2024-03-03" },
    {"label":"zyBooks Week 9 due", "date":"2024-03-10" },
    {"label":"zyBooks Week 10 due", "date":"2024-03-17" },
    {"label":"Quiz 1", "date":"2024-01-19" },
    {"label":"Quiz 2", "date":"2024-02-02" },
    {"label":"Quiz 3", "date":"2024-02-16" },
    {"label":"Quiz 4", "date":"2024-03-01" },
    {"label":"Quiz 5", "date":"2024-03-15" },
    {"label":"Final Exam (12pm - 2pm)", "date":"2024-03-20" },
    {"label":"W24 instruction ends", "date":"2024-03-15" },
    {"label":"W24 qtr ends", "date":"2024-03-22" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
